import Header from '@/components/Header';
import { ThemeProvider } from '@/components/theme-provider';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Script from 'next/script';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <head>
        <Script
          type='module'
          src='https://dev-cdn.synt.com/synt-opt-in-script.js'
          async
          defer
          strategy='lazyOnload'
        ></Script>
        <Script
          type='text/javascript'
          id='synt-opt-in-script'
          strategy='lazyOnload'
        >
          {`window.sn_meta = window.sn_meta || {
    "app_id": "fd7ff2b4-31bc-4087-ab52-d137bd4d3037",
    "app_signature": "0cec6085-2dce-4db3-92a4-80aeec81be7e",
    "app_worker_path": ".././synt-worker-script.js",
    "app_version": "v1.0.1",
    "platform": "media",
  };`}
        </Script>
      </head>
      <body className={inter.className}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
